<a href="https://colab.research.google.com/github/gravity0717/Capstone/blob/main/MultiCNN_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import json 
import tarfile 
import torch 
from torch.utils.data import Dataset
import math
from PIL import Image
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
def cleaningjson(path):
  with open(path, 'r') as j:
     train = json.loads(j.read())

  _df=pd.DataFrame(train)
  _df.drop(labels=["name",	"views" ,"image","date","set_url","desc"],axis=1)

  _like_list=list()
  _logs=[]
  _like_list=_df['likes']

  for i in _like_list:
    i=math.log(i)
    _logs.append(i)
    
  _df['log_like']=logs

  return _df

path='/content/drive/MyDrive/Polyvore/train_no_dup.json'

with open(path, 'r') as j:
     train = json.loads(j.read())

train_df=pd.DataFrame(train)

train_df.head()

cleaningjson(path)
train_df

,name,views,items,image,likes,date,set_url,set_id,desc
0,Casual,8743,"[{'index': 1, 'name': 'mock neck embroidery su...",http://ak1.polyvoreimg.com/cgi/img-set/cid/214...,394,One month,http://www.polyvore.com/casual/set?id=214181831,214181831,A fashion look from January 2017 by beebeely-l...
1,Being a Vans shoe model with Luke. Idk about t...,188,"[{'index': 1, 'name': 'nirvana distressed t-sh...",http://ak1.polyvoreimg.com/cgi/img-set/cid/120...,9,Two years,http://www.polyvore.com/being_vans_shoe_model_...,120161271,A fashion look from April 2014 featuring destr...
2,These Chanel bags is a bad habit .x,562,"[{'index': 1, 'name': 'monki singlet', 'price'...",http://ak1.polyvoreimg.com/cgi/img-set/cid/143...,32,Two years,http://www.polyvore.com/these_chanel_bags_is_b...,143656996,12.19.14
3,Avenger/Supernatural prp,2613,"[{'index': 1, 'name': 'tops', 'price': 18.0, '...",http://ak2.polyvoreimg.com/cgi/img-set/cid/186...,88,One year,http://www.polyvore.com/avenger_supernatural_p...,186627934,A fashion look from January 2016 by alyssaclai...
4,Boho (39),62,"[{'index': 1, 'name': 'yoins leather sexy v-ne...",http://ak2.polyvoreimg.com/cgi/img-set/cid/206...,3,5 months,http://www.polyvore.com/boho_39/set?id=206969379,206969379,A fashion look from August 2016 by kate-goida ...
...,...,...,...,...,...,...,...,...,...
17311,2.15.17,183,"[{'index': 1, 'name': 'raey deep v-neck silk c...",http://ak1.polyvoreimg.com/cgi/img-set/cid/216...,117,4 days,http://www.polyvore.com/15.17/set?id=216801059,216801059,A fashion look from February 2017 by kianahall...
17312,tweed,2428,"[{'index': 1, 'name': 'michael kors printed bo...",http://ak1.polyvoreimg.com/cgi/img-set/cid/190...,382,One year,http://www.polyvore.com/tweed/set?id=190488700,190488700,A fashion look from February 2016 by drigomes ...
17313,TV Style: Pretty Little Liars,2184,"[{'index': 1, 'name': 'color block fit flare m...",http://ak2.polyvoreimg.com/cgi/img-set/cid/187...,398,One year,http://www.polyvore.com/tv_style_pretty_little...,187504514,A fashion look from January 2016 by vanjazivad...
17314,60-Second Style: Work Wear,3147,"[{'index': 1, 'name': 'patchwork fit flare dre...",http://ak2.polyvoreimg.com/cgi/img-set/cid/211...,440,Three months,http://www.polyvore.com/60-second_style_work_w...,211085207,A fashion look from November 2016 by beebeely-...
17315,Mini Dress: The Glamour Edition,111,"[{'index': 1, 'name': 'burberry kensington lea...",http://ak1.polyvoreimg.com/cgi/img-set/cid/211...,21,Three months,http://www.polyvore.com/mini_dress_glamour_edi...,211686294,A fashion look from November 2016 by footsteps...

In [3]:
train_df.drop(labels=["name",	"views" ,"image","date","set_url","desc"],axis=1,inplace=True)

In [4]:
like_list=list()
logs=[]
like_list=train_df['likes']

for i in like_list:
  i=math.log(i)
  logs.append(i)
  
train_df['log_like']=logs # label 

train_df

,items,likes,set_id,log_like
0,"[{'index': 1, 'name': 'mock neck embroidery su...",394,214181831,5.976351
1,"[{'index': 1, 'name': 'nirvana distressed t-sh...",9,120161271,2.197225
2,"[{'index': 1, 'name': 'monki singlet', 'price'...",32,143656996,3.465736
3,"[{'index': 1, 'name': 'tops', 'price': 18.0, '...",88,186627934,4.477337
4,"[{'index': 1, 'name': 'yoins leather sexy v-ne...",3,206969379,1.098612
...,...,...,...,...
17311,"[{'index': 1, 'name': 'raey deep v-neck silk c...",117,216801059,4.762174
17312,"[{'index': 1, 'name': 'michael kors printed bo...",382,190488700,5.945421
17313,"[{'index': 1, 'name': 'color block fit flare m...",398,187504514,5.986452
17314,"[{'index': 1, 'name': 'patchwork fit flare dre...",440,211085207,6.086775
17315,"[{'index': 1, 'name': 'burberry kensington lea...",21,211686294,3.044522

In [5]:
with open('/content/drive/MyDrive/Polyvore/category 재정리_top.txt') as f: 
  top_list=[]
  for line in f:
    tmp=line.split()
    top_list.append(tmp[0])
    
with open('/content/drive/MyDrive/Polyvore/category 재정리_bot.txt') as f: 
  bot_list=[]
  for line in f:
    tmp=line.split()
    bot_list.append(tmp[0])

with open('/content/drive/MyDrive/Polyvore/category 재정리_shoes.txt') as f: 
  shoes_list=[]
  for line in f:
    tmp=line.split()
    shoes_list.append(tmp[0])

with open('/content/drive/MyDrive/Polyvore/category 재정리_outer.txt') as f: 
  outer_list=[]
  for line in f:
    tmp=line.split()
    outer_list.append(tmp[0])

'''

'''






bot_list

['7',
 '8',
 '9',
 '10',
 '27',
 '28',
 '29',
 '55',
 '237',
 '238',
 '239',
 '240',
 '241',
 '253',
 '254',
 '255',
 '278',
 '279',
 '280',
 '287',
 '288',
 '4452',
 '4458',
 '4459']

In [5]:
top , bot , shoes , outer => label

In [6]:
def rearr_clths(category_id):
  category_id=str(category_id)
  if category_id in top_list:
   return 'top'
  elif category_id in bot_list:
   return 'bottom'
  elif category_id in shoes_list:
    return 'shoes'
  elif category_id in outer_list:
    return 'outer'
  else :
    return 'wait to drop'

def arr(path):
  path =str(path)
  if category_id in top_list:
   return 'top'
  elif category_id in bot_list:
   return 'bottom'
  elif category_id in shoes_list:
    return 'shoes'
  elif category_id in outer_list:
    return 'outer'
  else :
    return 'wait to drop'



print(rearr_clths(4495))

top

In [ ]:
for outfits in train_df['items']:
  for item in outfits: #outfits 는 list, 그 안에 dict 자료형의 item 
    item['categoryid']=rearr_clths(item['categoryid'])
    print(item['categoryid'])

# making polyvore dataset 

1.   항목 추가
2.   항목 추가

In [8]:
import PIL 
import glob



class Polyvore(Dataset):
  def __init__(self,path,train=True,transform=None):
        self.path = path
        if train==True:
            self.json_path='/content/drive/MyDrive/Polyvore/train_no_dup.json'
        else :
            self.json_path='/content/drive/MyDrive/Polyvore/test_no_dup.json'
        
        self.dataframe=cleaningjson(json_path) 
        for outfits in self.dataframe['items']:
          for item in outfits: #outfits 는 list, 그 안에 dict 자료형의 item 
            item['categoryid']=rearr_clths(item['categoryid'])
        self.log_like=self.dataframe['log_like']
            #print(item['categoryid'])



  def __len__(self):
    return len(self.label)
  # def wait to drop 

  def __getitem__(self, idx):
    #인덱스
    self.idx=idx
    #사진
    img_path ="/images" +self.dataframe['set_id'][self.idx] + self.dataframe['item']['index']

    top = Image.open(img_path)
    bot = 
    shoes= 
    outer =
    #레이블 
    label=self.log_like[idx]
    
    with tarfile.open(self.img_path,'r') as f:
      # category 는 Gdrive 내 polyvore 폴더 속 category-id 를 통해서 다시 가공해야 함 
      return top,bot,shoes,outer,label

In [9]:
mem=list()
img_path='/content/drive/MyDrive/Polyvore/polyvore-images.tar'
with tarfile.open(img_path,'r') as f:
  mem=f.getmembers()

KeyboardInterrupt: ignored

In [ ]:
!tar tvf /content/drive/MyDrive/Polyvore/polyvore-images.tar

#이름 구성 : images/set_id/index_number 로 구성

# build multi-cnn architecture

In [ ]:
'''

transfer learning 


새로 훈련할 데이터가 적지만 original 데이터와 유사할 경우
데이터의 양이 적어 fine-tune (전체 모델에 대해서 backpropagation을 진행하는 것) 은 over-fitting의 위험이 있기에 하지 않습니다.
새로 학습할 데이터는 original 데이터와 유사하기 때문에 이 경우 최종 linear classfier 레이어만 학습을 합니다.

새로 훈련할 데이터가 매우 많으며 original 데이터와 유사할 경우
새로 학습할 데이터의 양이 많다는 것은 over-fitting의 위험이 낮다는 뜻이므로, 전체 레이어에 대해서 fine-tune을 합니다.

새로 훈련할 데이터가 적으며 original 데이터와 다른 경우
데이터의 양이 적기 때문에 최종 단계의 linear classifier 레이어를 학습하는 것이 좋을 것입니다. 반면서 데이터가 서로 다르기 때문에 거의 마지막부분 (the top of the network)만 학습하는 것은 좋지 않습니다. 서로 상충이 되는데.. 이 경우에는 네트워크 초기 부분 어딘가 activation 이후에 특정 레이어를 학습시키는게 좋습니다.

새로 훈련할 데이터가 많지만 original 데이터와와 다른 경우
데이터가 많기 때문에 아예 새로운 ConvNet을 만들수도 있지만, 실적적으로 transfer learning이 더 효율이 좋습니다. 전체 네트워크에 대해서 fine-tune을 해도 됩니다.

'''

from torchvision import models

model_pt=models.vgg16(pretrained=True)


for p in model_pt.parameters():
  p.requires_grad=False # 가중치가 학습되지 않도록 함 
#in_features?


print(model_pt.features)

In [ ]:

'''
pretrained model VGG 16 VGG 19 AlexNet LeNet .... Transfer learning 
'''
import torch.nn.functional as F
from torch import nn
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.relu = nn.ReLU(inplace=True)
        self.l1   =  nn.Linear(163840,1024)
        self.l2   =  nn.Linear(1024,1) # regression 이기 때문에 마지막 차원 1 
        self.VGG16 = model_pt.features
        
    def forward(self, top ,bot,shoes,outer,hat):
        top= self.VGG16(top)   #216*216
        bot = self.VGG16(bot)  #
        shoes = self.VGG16(shoes) #
        outer=self.VGG16(outer)   #
        N ,_,_,_ = top.size()
        top = top.view(N,-1)
        bot = bot.view(N,-1)
        shoes = shoes.view(N,-1)
        outer = outer.view(N,-1)
        z = torch.cat((top,bot,shoes,outer,hat),1)
        z = self.l1(z)
        z = self.relu(z)
        z = self.l2(z)
        return z

In [ ]:
from torchvision import models
from torchsummary import summary

In [ ]:

# 모델 시각화 
model=Model()
!pip install torchsummary

from torchsummary import summary
model=Model()
summary(model,[(3,256,256),(3,256,256),(3,256,256),(3,256,256),(3,256,256)])

# Train

# Evaluation / Visualization